#!/usr/bin/env python
#
# Copyright (C) 2022 Martincz Gao
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import collections
import os
import rule
import sys
from deepmerge import always_merger
from ruamel.yaml import YAML

def main():

    yaml = YAML()
    yaml.allow_unicode = True
    yaml.explicit_start = False
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)

    # 读取所有配置
    with open('configs/base.yaml') as fp:
        cfg_base = yaml.load(fp)

    try:
        with open('configs/custom.yaml') as fp:
            cfg_custom = yaml.load(fp)
            if cfg_custom is None:
                raise FileNotFoundError
    except FileNotFoundError:
        print('未配置 configs/custom.yaml 文件！')
        sys.exit(1)

    cfg_rule = rule.getRules()

    # 检查重复项
    # print([item for item, count in collections.Counter(cfg_rule['rules']).items() if count > 1])

    # 生成最终配置
    cfg_final = cfg_base.copy()
    cfg_array = [cfg_base, cfg_custom, cfg_rule]
    for cfg in cfg_array:
        cfg_final.update(cfg)

    with open('configuration.yaml', 'w') as fp:
        yaml.dump(cfg_final, fp)


if __name__ == '__main__':
    main()