# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
dns:
  enable: false
  listen: :53
  ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: redir-host # or fake-ip
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - tls://dns.rubyfish.cn:853

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  fallback:
    - tls://101.101.101.101
    - tls://8.8.4.4:853
    - tls://1.0.0.1:853

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  fallback-filter:
    geoip: true
  #   geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
        #NetFlix
      - '+.netflix.com.edgesuite.net'
      - '+.fast.com'
      - '+.netflix.com'
      - '+.netflix.net'
      - '+.netflixdnstest0.com'
      - '+.netflixdnstest1.com'
      - '+.netflixdnstest2.com'
      - '+.netflixdnstest3.com'
      - '+.netflixdnstest4.com'
      - '+.netflixdnstest5.com'
      - '+.netflixdnstest6.com'
      - '+.netflixdnstest7.com'
      - '+.netflixdnstest8.com'
      - '+.netflixdnstest9.com'
      - '+.nflxext.com'
      - '+.nflximg.com'
      - '+.nflximg.net'
      - '+.nflxso.net'
      - '+.nflxvideo.net'
      #Linkedin
      - '+.linkedin.com'
      - '+.licdn.com'
      #proxy
      - '+.renzhe.cloud'
      - '+.nivod4.tv'
      - '+.nivodz.com'
      - '+.cloudflare.com'
      - '+.onetrust.com'
      - '+.plausible.io'
      - '+.fhjasokiwq.com'
      - '+.recaptcha.net'
      - '+.biggggg.com'
      - '+.newpppp.com'
      - '+.ofalibi.com'
  
  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'