# 本地局域网地址
- name: "Lan"
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/Lan/Lan.yaml"

# 反劫持
- name: "Hijacking"
  group: "Hijacking"
  ruleset: "rules/blackmatrix7/Hijacking/Hijacking.yaml"

# ChinaMedia
- name: "ChinaMedia" 
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/ChinaMedia/ChinaMedia.yaml"

# China
- name: "China" 
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/China/China.yaml"

# AsianMedia
- name: "AsianMedia" 
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/AsianMedia/AsianMedia.yaml"

# GlobalMedia
- name: "GlobalMedia"
  group: "GlobalMedia"
  ruleset: "rules/blackmatrix7/GlobalMedia/GlobalMedia.yaml"

# Apple
- name: "Apple" 
  group: "Apple"
  ruleset: "rules/blackmatrix7/Apple/Apple.yaml"

# AppleTV
- name: "AppleTV"
  group: "GlobalMedia"
  ruleset: "rules/blackmatrix7/AppleTV/AppleTV.yaml"

# Facebook
- name: "Facebook"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Facebook/Facebook.yaml"

# Twitter
- name: "Twitter"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Twitter/Twitter.yaml"

# Google
- name: "Google"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Google/Google.yaml"

# OneDrive
- name: "OneDrive"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/OneDrive/OneDrive.yaml"

# Telegram
- name: "Telegram"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Telegram/Telegram.yaml"

# Speedtest
- name: "Speedtest"
  group: "Speedtest"
  ruleset: "rules/blackmatrix7/Speedtest/Speedtest.yaml"